### PR TITLE
Master

### PR DESCRIPTION
**Pull request by snp1606**

### CODE REVIEW

**Comment by fracz** [comment]
Do you have any trouble with solving exercises?

You need to execute the commands available on the [git exercises page](http://gitexercises.fracz.com/) and push your solutions to the repo there, not to the github :-)

**Comment by snp1606** [comment]
Hi

I am new to Git and trying to do some handson exercise.

On my local hard drive I have tried to use 'Git Bash Here' and on the CLI
when I am trying to give 'git clone url' then I am getting below  error.

fatal: unable to access URL: The requested URL returned error: 503

Please suggest

Thanks
Sachin

**Comment by fracz** [comment]
What is the full `git clone` command you are trying the execute?

**Comment by snp1606** [comment]
Steps I have done so far...

1.Created a directory called Git Exercise in my local drive.

2. Inside this directory I initialised by using command: git init

3. Then I am using the first command as mentioned in 'How to start?'
section of the Home page.

git clone https://gitexercises.fracz.com/git/exercises.git

Then I am getting the fatal error.

fatal: unable to access ' https://gitexercises.fracz.com/git/exercises.git/'
: The requested URL returned error : 503

**Comment by fracz** [comment]
Unfortunately, the platform does not run under HTTPS yet.

Try `git clone http://gitexercises.fracz.com/git/exercises.git`

**Pull request closed without merging**
